name    'andschwa-ghost'
version '0.2.0'
source 'git://github.com/andschwa/puppet-ghost.git'
author 'Andrew Schwartzmeyer'
license 'GNU Affero'
summary 'Install and Manage Ghost Blog'
description 'Installs, configures, and manages the Ghost Blogging Platform for Ubuntu'
project_page 'https://github.com/andschwa/puppet-ghost'

dependency 'maestrodev/wget', '>= 1.1.0'
dependency 'puppetlabs/apt', '>= 1.4.0'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
